run-dist:
		./build/install/app/bin/app

clean:
		./gradlew clean

run:
		./gradlew run

install:
		./gradlew clean install

lint:
		./gradlew checkstyleMain

test:
		./gradlew test

setup:
		./gradlew wrapper --gradle-version 8.5


